### ISSUE TITLE
pronouns

### ISSUE THREAD

**Issue by kyllian1212** [kyllian1212/Rin-rewrite#16]
have a system to add pronouns (and create the role if the pronouns dont exist already)

**Comment by toxin-x** [comment]
I don't think this is truly necessary anymore due to the channels and roles function of communities

**Comment by kyllian1212** [comment]
it was a bit of a different system than the classic roling we have rn. the idea was:
/pronouns [pronouns1] [pronouns 2]

example:
/pronouns she her
would check if the "she/her" role exists, create it and move it to the right place in the role hierarchy if it doesn't exist, and then give it out to the member.

you give the bot the "boundaries" for the pronouns role (the -------pronouns------- role thing) so that it knows where to move the newly created role (if it doesnt exist) via /set_pronouns_boundaries for example or something

**Comment by kyllian1212** [comment]
not necessary anymore due to discord having a native function for pronouns
