### ISSUE TITLE
[!!] /irene command out of date

### ISSUE THREAD

**Issue by starfoxdot64** [kyllian1212/Rin-rewrite#36]
I don't know what this was meant to show, but I stumbled across it while looking into what Rin's dad's message was. Just so happened to notice it just after. Here's the permalink to the line in question - might be worth using something like catbox.moe instead for image hosting, since Discord changed their media link structure for auto-expiration. 

This appears to be the only instance of a broken Discord link though :v

--

https://github.com/kyllian1212/Rin-rewrite/blob/f59f3fcf24e0a81fa5aa308ab5369ef06f58b906/cogs/commands/fun.py#L146

**Comment by toxin-x** [comment]
The expiry doesn't apply when loaded on discord because the client will add the refresh token automatically (otherwise no files on discord would work). It is only an issue accessing files outside of discord! Thank you though!
